### ISSUE TITLE
Actix.

### ISSUE THREAD

**Issue by uwejan** [akozhemiakin/akt#2]
Hello there,
I am comming from actix actors background, it is working really good, especially with StreamHandlers, and webscokets, Now the project is growing and needs to put in place some sqlx queries, and that added a ton of issues, as sqlx is async, and self can not move while holding db connection.
I am wondering if this crate would be an easy convert from actix, without lossing much, and gaining async await handle?

Thank you.

**Comment by akozhemiakin** [comment]
Hello Saddam,

Indeed, Actix is a more mature and battle-tested lib compared to Akt. At the moment, Akt does not possess all the features that Actix offers. Instead, Akt focuses primarily on the core aspects of the actor model, with plans to progressively enhance its capabilities.

Regarding your inquiry, I am not well-acquainted with your project and its specific requirements. However, I recommend reviewing the Overview section in the Readme, as it outlines almost all of Akt's current functionality. This may help you in determining whether Akt is suitable for your needs.

Please let me know if I can provide any additional assistance.

**Comment by uwejan** [comment]
Hey @akozhemiakin Thank you for taking the time to look into this.
I am actually still studying my options trying here and there, It is though really helpfull to know that maintainers are active and helpful. 
The issue can be closed for now, I shall comeback things changed.
Thank you.
